#!/bin/sh

#check for error:
function cfo() {
    if [ $? != 0 ]; then
        echo "-- Error on $1"
        exit $?
    else
        echo "++ Success on $1"
    fi
}

if [ -f swhx.zip ]; then
	rm swhx.zip
	cfo "removing previous zip package"
fi

if [ -d swhx ]; then
	rm -R swhx
	cfo "removing previous package source tree"
fi

cd run
haxe compile.hxml
cd ..

#root
mkdir swhx
cfo "creating source tree folder"
cp haxelib.xml swhx
cfo "copying haxelib xml config"
cp CHANGES.txt swhx
cfo "copying CHANGES.txt"
cp LICENSE.txt swhx
cfo "copying LICENSE.txt"
cp run/run.n swhx
cfo "copying post flight Neko run app"

#haxe api
cd api/haxe/swhx
svn export . ../../../swhx/swhx
cfo "exporting haXe API from SVN"
cd ../../..

#flash api
mkdir swhx/api
cfo "creating ActionScript API folder"
cd api/actionscript
svn export . ../../swhx/api/actionscript
cfo "exporting ActionScript API from SVN"
cd ../..

# ndlls
mkdir -p swhx/ndll/Windows
cfo "creating NDLL Windows folder"
cp bin/win/swhx.ndll swhx/ndll/Windows/swhx.ndll
cfo "copying SWHX.ndll for Windows"
mkdir swhx/ndll/Mac
cfo "creating NDLL Mac folder"
cp bin/mac/swhx.ndll swhx/ndll/Mac/swhx.ndll
cfo "copying SWHX.ndll for Mac"
mkdir swhx/ndll/Linux
cfo "creating NDLL Linux folder"
cp bin/linux/swhx.ndll swhx/ndll/Linux/swhx.ndll
cfo "copying SWHX.ndll for Linux"

#tools
mkdir swhx/tools
cfo "creating Tools folder"
cp -R bin/mac/swhx.app swhx/tools/swhx.app
cfo "copying Mac Boot loader"
chmod -R 755 swhx/tools/swhx.app
cfo "cleanip Mac Boot loader"
rm -rf swhx/tools/swhx.app/.svn swhx/tools/swhx.app/*/.svn swhx/tools/swhx.app/*/*/.svn
cfo "updating rights on Mac Boot loader"
cp bin/win/swhx.exe swhx/tools/swhx.exe
cfo "copying Windows Boot loader"
cp bin/linux/swhx swhx/tools/swhx
cfo "copying Linux Boot loader"
cp TOOLS.README.txt swhx/tools/README.txt
cfo "copying TOOLS.README.txt"

#source
mkdir swhx/src
cfo "creating source folder"
cd src
svn export . ../swhx/src/src
cfo "exporting source files from SVN"
cd ../projects
svn export . ../swhx/src/projects
cfo "exporting project source files from SVN"
cd ../include
svn export . ../swhx/src/include
cfo "exporting include files from SVN"
cd ..

#samples
cd samples
svn export . ../swhx/samples
cfo "exporting samples from SVN"
cd ..

#zip it!
zip -q -r swhx.zip swhx
cfo "zipping package swhx.zip"
rm -rf swhx
